version: '3.8'

services:
  chathouse:
    image: chathouse:latest
    ports:
      - "5173:5173"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - chathouse-network

networks:
  chathouse-network:
    driver: bridge
