services:
  chathouse:
    build: .
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: npm run dev -- --host
    depends_on:
      - node